### ISSUE TITLE
ewww converter generates blank images

### ISSUE THREAD

**Issue by rosell-dk** [rosell-dk/webp-convert#10]

**Comment by rosell-dk** [comment]
I have tested on earlier versions of this library, and they all fail. So it seems that either the service has changed its API, or it is malfunctioning.

**Comment by rosell-dk** [comment]
As I have important deadlines, I unfortunately do not have time to investigate this further until after easter

**Comment by S1SYPHOS** [comment]
I‘ll try to look into API changes on the EWWW side.

**Comment by S1SYPHOS** [comment]
Seems to be as simple as this: „These requests should be sent to https://optimize.exactlywww.com/v2/“, so appending /v2/ should do the trick. Do you have an API key?

**Comment by S1SYPHOS** [comment]
Adressed this in 1d47061, and also refactored Ewww.php. Let me know if it works now!

**Comment by rosell-dk** [comment]
I'm purchacing a license. It is cheap and quicker than requesting a developer license again

**Comment by rosell-dk** [comment]
The ewww web service works. And the converter works with a working key.

**Comment by rosell-dk** [comment]
So the problem is that our converter creates a corrupt image instead of failing properly, when supplied with invalid license key

**Comment by rosell-dk** [comment]
Wrong key = the following response:
{"error":"invalid","t":"exceeded"}
And we currently just save that as an image.

Here is a hint of what we can do:
"The file type of the optimized file should be checked to ensure that a valid image was returned before replacing the original image with the optimized one, since an empty response is used to indicate no additional savings was achieved (or you could just check for an empty file)." [https://ewww.io/api/]

**Comment by rosell-dk** [comment]
"webp: 1. enables WebP generation, and will always return a WebP file even if it is not smaller than the original. It is up to the client software to determine if it is desirable to keep all WebP images received, or only those smaller than the original. This option runs in exclusion of all others, [...]"

**Comment by rosell-dk** [comment]
I added the following code to make it fail properly:
```php
        // The API does not always return images.
        // For example, it may return a message such as '{"error":"invalid","t":"exceeded"}
        // Messages has a http content type of ie 'text/html; charset=UTF-8
        // Images has application/octet-stream.
        // So verify that we got an image back.
        if (curl_getinfo($ch, CURLINFO_CONTENT_TYPE) != 'application/octet-stream') {
            curl_close($ch);
            return false;
        }

        // Not sure this can happen. So just in case
        if ($response == '') {
            return false;
        }
```

**Comment by S1SYPHOS** [comment]
So it still doesn’t work but at least it fails properly? :+1:

**Comment by rosell-dk** [comment]
I cannot tell if you are being sarcastic or not?

The converter works, in the sense that it generates images, when key is valid. There was no error there. Our problem was simply, that my developer key didn't work.

The problem was that the converter misbehaved when the key was invalid: It generated a blank image. That bug is fixed. Now it simply declines, so WebPConvert can skip to next converter - It fails in a proper way

**Comment by rosell-dk** [comment]
I have emailed you the key I bought, so you can test it working. Please take care not using more credits than you need! So once you have tested a successful conversion, you can uncomment where you set the key.
