### ISSUE TITLE
No supplied binaries found for OS:WINNT

### ISSUE THREAD

**Issue by Av1shay** [rosell-dk/webp-convert#105]
Hi,
I couldn't use cwebp for PNG images, got the error "No supplied binaries found for OS:WINNT".
Then I have notice in \vendor\rosell-dk\webp-convert\src\Converters\Cwebp.php, line 70 that the array `$suppliedBinariesInfo`  have the key "WinNT", but not "WINNT", hence `$suppliedBinariesInfo['WINNT']` is not set.
When I add the item `'WINNT' => [ 'cwebp.exe', '{WinNT binaries}']` to `$suppliedBinariesInfo` everything works.
Is it a bug? Or the capital letters have any meaning?

thanks!

**Comment by rosell-dk** [comment]
Sure looks like a bug!

**Comment by rosell-dk** [comment]
Ehm, the second element in the array should be the hash value. So, instead of ```'WINNT' => [ 'cwebp.exe', '{WinNT binaries}']```, it should be:  ```'WINNT' => [ 'cwebp.exe', '49e9cb98db30bfa27936933e6fd94d407e0386802cb192800d9fd824f6476873']
