### ISSUE TITLE
WebP Express Settings

### ISSUE THREAD

**Issue by TomPadapada** [rosell-dk/webp-convert#107]
Crashed images in my woocommerce shop. :( witamini.pl

How can I bring the images back? Disabling in General settings doesn't work. Turning of the plugin also deasn't work.

I'm on cloudflare.

I just want to bring the images back and turn the plugin.

**Comment by rosell-dk** [comment]
Check if there are any WebP Express rules left in the following files:
.htaccess
wp-content/.htaccess

Remove them, if there is.

They ought to have been removed when you uninstall the plugin, but it might have failed.

And clear the image cache on cloudflare
