### ISSUE TITLE
Not possible to convert multiple times

### ISSUE THREAD

**Issue by rosell-dk** [rosell-dk/webp-convert#11]
Calling WebPConvert::convert again results in this error:

Fatal error: Cannot redeclare stripFilenameFromPath() (previously declared in /mnt/Work/playground/webp-convert-test/webp-convert/WebPConvert.php:101) in /mnt/Work/playground/webp-convert-test/webp-convert/WebPConvert.php on line 101

**Comment by S1SYPHOS** [comment]
Did you try that one before? In my opinion, changing the function name wouldn't cause this ..

**Comment by rosell-dk** [comment]
I'm doing more javascript than php, and have some javascript habbits, such as declaring functions inside functions. I'm simply moving the function to a static function

**Comment by rosell-dk** [comment]
I did the same thing in cwebp.php. Also fixing it there...

**Comment by rosell-dk** [comment]
I suppose the recent bug fixes calls for a 0.1.1 release ?

**Comment by rosell-dk** [comment]
But now that we have removed the script, it could be argued that we have made an incompatible API change ? In that case, we should actually move to 1.0.0. But before doing that, I suppose we should finish #8. What do you think?

**Comment by rosell-dk** [comment]
@S1SYPHOS

**Comment by S1SYPHOS** [comment]
In my opinion, changes until v1.0.0, feeling absolutely sure that everything‘s battle-tested & and working as expected, should be 0.2.0, 0.3.0, minor ones only on the last number as usual - jm2c
