### ISSUE TITLE
Supplied cweb binary does not execute

### ISSUE THREAD

**Issue by rosell-dk** [rosell-dk/webp-convert#12]
I get the following message:

Supplied binary found, but it exited with error code 126. Output was: Array ( [0] => nice: '/mnt/Work/playground/webp-convert-test/webp-convert/converters/cwebp/bin/cwebp-linux': Permission denied )

**Comment by S1SYPHOS** [comment]
Maybe `chmod +x cwebp-linux` ?

**Comment by rosell-dk** [comment]
The issue is with file permissions. After last update, cwebp-linux has 664 - so no permission to execute for anyone. 

Now, the question is what permissions would be the correct balance between security and that it works?

**Comment by rosell-dk** [comment]
770 ?

**Comment by rosell-dk** [comment]
Can we remove write permission? - or will git updates then fail?

**Comment by rosell-dk** [comment]
Perhaps 750 ?

**Comment by S1SYPHOS** [comment]
665 is read,write + read+write + read + execute, 664 just has no right to execute. I'd go with 665.

**Comment by rosell-dk** [comment]
665 will mean that group has permission to execute and write? So group can modify the executable and then run it. Is this perhaps a problem?

**Comment by S1SYPHOS** [comment]
645 then?

**Comment by rosell-dk** [comment]
It seems from first reply on this thread, that only the executable flag is actually stored in github:
https://www.reddit.com/r/git/comments/2sbzso/how_do_you_handle_file_permissions_when_using_git/

**Comment by rosell-dk** [comment]
It does not execute with 645. The execute flag from "all users" is apparently not inherited. So it should rather be 755 than 645

**Comment by S1SYPHOS** [comment]
Pretty smart way to handle this, Github!
Alright, then go for it :+1:
