### ISSUE TITLE
Bulk option

### ISSUE THREAD

**Issue by basserd** [rosell-dk/webp-convert#122]
Currently the bulk option that generates the `.webp` extension for files that don't have them yet searches within the WHOLE wp installation. I would really like the option to exclude certain folders. Since I only need the images within the uploads folder to have a `.webp` version.

**Comment by rosell-dk** [comment]
It is not the whole installation, but it is the whole *wp-content* folder. The main purpose of this is to get theme images converted.
But yes, I also believe that this should be optional.
But this option should not only apply to bulk conversions, but generally (the plugin can be configured to triggered image conversions in a variety of ways, and they too should respect such an option)

**Comment by rosell-dk** [comment]
Oh, you created this ticket in the wrong repo. This issue conserns [WebP Express](https://github.com/rosell-dk/webp-express).

I have created a ticket there:
https://github.com/rosell-dk/webp-express/issues/219
