### ISSUE TITLE
Add Expires header too

### ISSUE THREAD

**Issue by rosell-dk** [rosell-dk/webp-convert#126]
gtmetrix.com complains when no Expires header is sent - even when cache-control is set.

Perhaps we should set both, and not just cache-control?
See https://wordpress.org/support/topic/expires-headers-not-showing/#post-11390627

**Comment by pothi** [comment]
Direct quote from https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Expires ...

> If there is a Cache-Control header with the max-age or s-maxage directive in the response, the Expires header is ignored.

So, it is safe to use both.

**Comment by rosell-dk** [comment]
ok, thanks :)

**Comment by KevinBatdorf** [comment]
Actually, looks like it's just a syntax error in the default cache-control header setting. 

This works:

```
public, max-age=31536000, stale-while-revalidate=604800, stale-if-error=604800
```

But the plugin will default to `max-age:86400` with the `:` being the bug (also, maybe they should be cached for a year by default?)

**Comment by rosell-dk** [comment]
By default (when nothing is touched), the Cache-Control header option is set to "Do not set". And this result in the expected (no Cache-Control header). I am happy with this default. If it is set to one year per default, it will take a year to completely undo it. Not setting the header results in browsers caching only a short period, but over time (if resource has not changed) increasingly longer.

**Comment by rosell-dk** [comment]
I found the bug your referred to. It is the default value that shows up, when you select "Custom". This default value is not used, unless you select Custom and leave it at that value. This should not affect too many. But of course I must fix it! Thanks for reporting!
