### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by rosell-dk** [rosell-dk/webp-convert#14]
I'm not happy with the side effects of calling `convert` (besides the conversion of the file). Right now, calling `convert` causes stuff to be echoed out (either as html text or image). It would be cleaner not to have these side effects, but rather have a way to receive that kind of information. Also, I'd like there to be a way for consumers to handle conversion errors.

**Comment by rosell-dk** [comment]
Proposal:

- The convert method returns a boolean indicating if convertion was successful
- WebPConvert supplies a static method or property that allows access to last error
- WebPConvert also supplies a way to the complete log of the last conversion
- WebPConvert no longer outputs anything, and also no longer maintains logic of what to do when errors occurs. Thus, the following options are removed: `WebPConvert::$serve_converted_image` and `WebPConvert::$serve_original_image_on_fail'. But it could perhaps provide some helpers

**Comment by rosell-dk** [comment]
Usage example of proposal:

```PHP
/* 
Example:
Echoing detailed results
*/

$source = $_SERVER['DOCUMENT_ROOT'] . '/webp-convert-test/images/test.png';
$destination = $_SERVER['DOCUMENT_ROOT'] . '/webp-convert-test/images/test.png.webp';
$quality = 90;
$strip_metadata = TRUE;

WebPConvert::set_preferred_converters(array('imagick','cwebp', 'gd'));

if (WebPConvert::convert($source, $destination, $quality, $strip_metadata)) {

  echo 'Image converted ok<br>';
  echo 'Here is how we did it:<br><br>'

  echo WebPConvert::last_conversion_log();
}
else {
  echo 'Oh no. Although we tried and tried, we failed converting your image.';
  echo 'Here is the log:<br><br>'

  echo WebPConvert::last_conversion_log();

}
```

**Comment by rosell-dk** [comment]
Example, when wanting to serve images:

```
/* 
Example:
Serving converted images
*/

// We are going to serve an image. 
// Textual content will corrupt the image, so we prevent PHP from outputting error messages
ini_set('display_errors', 'Off');

$source = $_SERVER['DOCUMENT_ROOT'] . '/webp-convert-test/images/test.png';
$destination = $_SERVER['DOCUMENT_ROOT'] . '/webp-convert-test/images/test.png.webp';
$quality = 90;
$strip_metadata = TRUE;

WebPConvert::set_preferred_converters(array('imagick','cwebp', 'gd'));

if (WebPConvert::convert($source, $destination, $quality, $strip_metadata)) {

  // everything went fine.
  // Now, we serve the converted image  
  header('Content-type: image/webp');
  readfile($destination);
}
else {
  // Get the error code and do something appropriate
  $error_code = WebPConvert::last_error_code();

  switch ($error_code) {
    case WebPConvert.E_SOURCE_FILE_NOT_FOUND:
    case WebPConvert.E_UNSUPPORTED_FILE_EXTENSION:

      WebPConvert.output_last_error_message_as_image();
      break;

    case WebPConvert.E_DESTINATION_NOT_WRITABLE:
    case WebPConvert.E_NO_CONVERTERS_COULD_CONVERT:
    
      WebPConvert.output_original_image();
      break;    
  }  
}
```

**Comment by rosell-dk** [comment]
How does it sound, @S1SYPHOS ?

**Comment by rosell-dk** [comment]
Or is it better to throw exceptions ?

**Comment by rosell-dk** [comment]
oh. better get back to my deadlines...

**Comment by S1SYPHOS** [comment]
@rosell-dk Hey there, just a lot to process and I got some deadlines, too right now :slightly_smiling_face: 
I'll think about this and maybe incorporate it in patch-1 branch!

**Comment by rosell-dk** [comment]
Sounds good!
Btw, Monday, I'm off for easter holliday. Going to your country, actually. But not quite as far south as your residence. First a couple of days in Hamburg, next some days in Hannover, where my wife lived some time.

**Comment by S1SYPHOS** [comment]
I'm all for throwing exceptions. What people using this library want to achieve is generating WebP images, regardless their individual setup, shared hosting, installed packages, .. and since we're going for an "out-of-the-box" approach, I'd say providing logs is unnecessary.

I'll remove the logging functionality on `patch-1`, and we'll integrate exceptions soon. Also, I was thinking utilising `PHPUnit` and TravisCI for automated testing, what do you say? Happy easter!

**Comment by rosell-dk** [comment]
Ok, go :)

**Comment by S1SYPHOS** [comment]
May I ask, what do you think about turning `convert()` into a non-static function? Have you read about possible pros/cons?

**Comment by rosell-dk** [comment]
The thought has occured to me. But as it is primarily for the sideeffect, the funtion is for, I see no use cases for making instances of the class. What would you want to do with the objects? - besides getting log and status of the conversion, but I aggree that this is of secondary value

**Comment by rosell-dk** [comment]
Typically, you will just want to do a conversion and be able to handle errors. For that, a static function is most suitable, it seem

**Comment by S1SYPHOS** [comment]
Well, one thing though:
I don't see how you would access `$current_conversion_vars`, since after calling `WebPConvert::convert()`, it's just an empty array, no? For an instance, those would be saved, or am I missing something obvious?

**Comment by rosell-dk** [comment]
I forgot about prefered converters (im not at the computer). But we could
keep that static no matter if we make convert atatic or not. But actually,
is it not better to supply it as an extra optional parameter to the concert
call?

Den man. 26. mar. 2018 21.19 skrev Martin Folkers <notifications@github.com
