### ISSUE TITLE
error when convert png images

### ISSUE THREAD

**Issue by artayoga2** [rosell-dk/webp-convert#161]
When i try to convert png to webp, i get error notifications :

Fatal error: Uncaught WebPConvert\Converters\Exceptions\ConversionDeclinedException: PNG file skipped. GD is configured not to convert PNGs in C:\wamp64\www\tutorial\composer\vendor\rosell-dk\webp-convert\src\Converters\Gd.php on line 95

How do i handle it?? thank's

**Comment by rosell-dk** [comment]
You simply set the *skip-pngs* option to *false*
