### ISSUE TITLE
setimageoption() might not to be generally available in Gmagick?

### ISSUE THREAD

**Issue by rosell-dk** [rosell-dk/webp-convert#169]
Scrutinizer complains: "The method setimageoption() does not exist on Gmagick"

**Comment by nosilver4u** [comment]
Hi Bjorn, I was looking for a way to implement the -sharp_yuv flag for WebP in Gmagick, and stumbled across some of your code, which was very helpful! I had checked with the maintainer for GraphicsMagick, and he wasn't sure how to do it, so I was glad someone actually cracked this nut already!
I noticed you had sort of a question in the code, as to whether the "setimageoption" method had always existed, so I did some digging in the gmagick repo and found where it was added back in 2016: https://github.com/vitoc/gmagick/blob/e5420bae7cb6242f7a94afa27a0f4c3eca4de764/gmagick_methods.c

Cheers!

**Comment by rosell-dk** [comment]
Thanks!
