### ISSUE TITLE
Preferred converters

### ISSUE THREAD

**Issue by rosell-dk** [rosell-dk/webp-convert#17]
I'm not sure it is such a good idea with the concept of "preferred converters", and that the script always tries all converters, and only allows changing the order. Mostly, because it is not intuitive. I guess it may come as a surprise that after calling setPreferredConverters(array('ewww')), all converters will still be tried - that it just moves 'ewww' up to the front.

On the other hand, this may be exactly what you want. If for example you decided for yourself that 'cwebp' is the best converter, you can call setPreferredConverters without having to supply the complete list of converters. And when new converters are added to webp-convert, you will not miss out on them.

On the other other hand, there may be cases where you want to limit the converters tried. For example in order to test if a converter works. This may for example be useful, if you have an admin interface, where you allow users some insight and configuration options.

Another thing about the option is that it is currently set with a static call. The other static properties are being removed with the next PR. So this one stands alone.

Yet another thing is that the default order ought to be set to something wise. Right now the default order is not decided consciously.

I have two proposals. We should select between them (or come up with another solution)

**Proposal A**
- We keep the setPreferredConverters method as is (but perhaps rename it, if we can find a better name)
- In addition, we add an $converters as an extra optional option in convert. If supplied, only those converters listed here, will be tried out. Otherwise, all converters will be tried - in the order determined by defaults, and calls to setPreferredConverters.

**Proposal B**
- We remove setPreferredConverters method
- We add an $converters as an extra optional option in convert. If supplied, only those converters listed here, will be tried out. Otherwise all converters will be tried, in default order.

**Comment by rosell-dk** [comment]
What do you think, @S1SYPHOS ?

**Comment by rosell-dk** [comment]
The question boils down to whether we want to keep the option for reordering converters with setPreferredConverters. I guess the option has its merits. But it also introduces some complexity, which I guess is rarely needed.

**Comment by rosell-dk** [comment]
a better name would perhaps be `reorderConverters`

**Comment by S1SYPHOS** [comment]
I'd go for something like `setConverters` or `defineConverters` with two parameters: first param being an array (like right now), second (optional) param being whether the passed converters should be used exclusively or not (default being what we currently have).

**Comment by rosell-dk** [comment]
So you prioritize reordering. 
There are also a couple of good things about it. For example, that it really doesn't hurt to have backup converters waiting, should your preferred converter fail. And sometimes users may be surprised that a converter fails. For example, one may not have considered that gd per default fails for PNG's. 
So yes, we should not encourage that users remove converters.

**Comment by rosell-dk** [comment]
A related note:
I guess we should supply a public method for getting available converters - to facilitate things like an admin interface. 

With such method in place, users would be able to do reordering on their own. But no, it would not be practical, and it would not encourage users to keep all converters on the list.

From the discussion so far, we can rule out proposal B.

**Comment by S1SYPHOS** [comment]
True, but I'd suggest taking this on after the v1.0.0 release, what do you say? While I'm at it: I added a basic `.travis.yml`, but, same as with Packagist, you have [activate it](https://travis-ci.org).

**Comment by rosell-dk** [comment]
I really believe we should get this settled before the version release, as it is API changing. We should minimize releases that are API changing.

**Comment by S1SYPHOS** [comment]
I'm on it, hold on ..

**Comment by S1SYPHOS** [comment]
```php

    public static $preferredConverters = [];
    public static $excludeDefaultBinaries = false;

    // ...

    public static function setConverters($array, $exclude = false)
    {
        self::$preferredConverters = $array;

        if ($exclude) {
            self::$excludeDefaultBinaries = true;
        }
    }

    // ...

    public static function getConverters()
    {
        // Prepare building up an array of converters
        $converters = [];

        // Saves all available converters inside the `Converters` directory to an array
        $availableConverters = array_map(function ($filePath) {
            $fileName = basename($filePath, '.php');
            return strtolower($fileName);
        }, glob(__DIR__ . '/Converters/*.php'));

        // Checks if preferred converters match available converters and adds all matches to $converters array
        foreach (self::$preferredConverters as $preferredConverter) {
            if (in_array($preferredConverter, $availableConverters)) {
                $converters[] = $preferredConverter;
            }
        }

        if (self::$excludeDefaultBinaries) {
            return $converters;
        }

        // Fills $converters array with the remaining available converters, keeping the updated order of execution
        foreach ($availableConverters as $availableConverter) {
            if (in_array($availableConverter, $converters)) {
                continue;
            }
            $converters[] = $availableConverter;
        }

        return $converters;
    }
```

**Comment by rosell-dk** [comment]
The name `setConverters` is perhaps not the best choice, when default is to reorder, rather than set.

**Comment by S1SYPHOS** [comment]
The latest commit 1db125e will close this issue once it gets merged.

// Update: True, but it corresponds well with `getConverters()` and in some way it 'sets' the converters, just not exclusively, but in another order

**Comment by rosell-dk** [comment]
I guess the only use case for wanting to set exclusively is when you want to test a single converter.

**Comment by rosell-dk** [comment]
Do you prefer a static method rather than an extra argument?
I think I prefer an extra argument. But if we also need an "exclusive" argument, I don't

**Comment by rosell-dk** [comment]
True. But it is that _name_ of the function

**Comment by rosell-dk** [comment]
The confusion comes when you return to the code, and see that `setConverters` is called.

I myself got confused, when I returned to this code.
I wanted to test just one converter, and changed the array to array('ewww').

**Comment by S1SYPHOS** [comment]
In my opinion people don't need a warning since the feature they should be warned about is disabled by default, so turning it on is for people knowing what they do.

Well, I get now why this would be confusing at first .. but I guess that's because you have detailed knowledge about this library :sunny:

**Comment by rosell-dk** [comment]
You got a point there.
Actually, we should probably remove `setPreferredConverters` (or what it will be) from the example.

I guess we can also agree that the decision is not that important.
Still, we must decide on one thing or another.

* New static method VS new parameter to the `convert` call *
We can probably agree that general setting, that you only want to set once should be set with a static method. For example, we want converter options to be set separately, rather than in the convert call (#18). It is not something that you need to change from one `convert`-call to the next. When it comes to selection of converters, it is not always so. In most cases, you want to set it just once. But in rare cases, you need it to be different from call to call. So you could argue both ways. So I do not feel strongly about whether it will be the one or the other. I seems that you prefer not to have it part of the convert call? If yes, then ok, then

**Comment by rosell-dk** [comment]
... And I prefer two.

Mainly, in order to avoid confusion when returning to code. Usually, when you set something, you think about it in an explicit fashion. I do, at least.

But I also think that what the two things does are different enough to call for two methods. Changing the order of something is quite different from defining something explicitly. 

It is not that I don't see some sense in having just one method. The actions are after all not that different. And having an extra boolean option will bring attention to the fact that there is another option.

**Comment by rosell-dk** [comment]
So, lets vote ;)

**Comment by S1SYPHOS** [comment]
Alright, but what about someone declaring them being exclusive but not defining a custom set / order of converters? We'd have to test for that, and it seems inconvenient - you only need to **think** about converters being exclusive when they were **set at all**!

**Comment by S1SYPHOS** [comment]
.. which is possibly the strongest point: they are intrinsically connected!

**Comment by rosell-dk** [comment]
I'm not sure I follow.
I was thinking of a functionality that could be achieved like this:

- You rename your `setConverters` to `_setConverters` or something, and make it private
- You define a couple of new functions:

 ```php
public static function setConvertersExplicitly($convertersArray) {
  self::_setConverters($convertersArray, true)
}

public static function setConvertersOrder($convertersArray) {
  self::_setConverters($convertersArray, false)
}
```
As it is basically the same code, but split into two methods, we surely do not require further tests?

**Comment by S1SYPHOS** [comment]
Private methods cannot be tested afaik. Also, I think this would make the code harder to understand ..

**Comment by S1SYPHOS** [comment]
Also, prefixing functions with underscores smells like JavaScript :cat:

**Comment by rosell-dk** [comment]
heh :)

**Comment by rosell-dk** [comment]
Whoops. I realize I got to go fetch the kids now.

**Comment by S1SYPHOS** [comment]
Well, trust me, the current way is practical and easy to understand for people that are new to this library. For everyone already using it, nothing changes - except the name. Also, it’s very DRY.

**Comment by rosell-dk** [comment]
Perhaps we just need slightly different names. 
Or perhaps a method for pinpointing a single converter to be used

**Comment by rosell-dk** [comment]
We want to underexose the option to set explicitly as much as possible

**Comment by rosell-dk** [comment]
But still have available the option to use just a single converter

**Comment by daybugging** [comment]
I'm with @S1SYPHOS on this. The current way on branch `patch-1` is convincingly simple and achieves the goal easily. People get what they expect, and working with it is a breeze (which is why I already included this branch in my setup)!

**Comment by rosell-dk** [comment]
I argued that there is no need to set converters explicitly. There is just a need to be able to use a single converter.

The solution is straight forward:
We refactor convert, so it delegates the job of calling a single converter to a new public method.
It will keep things DRY, as well as provide a way to ask for a conversion using just a single converter

And we will not need the "explicly" option, which makes the act of understanding the library more complicated.

**Comment by S1SYPHOS** [comment]
Maybe another point in favor of the current solution is this: it‘s flexible, meaning that since I don‘t know what people are doing with this, they should be the ones making the decisions - like for whatever reason have **only** two specific converters try to convert an image.. my solution makes this dead simple :dancer:

**Comment by S1SYPHOS** [comment]
I seriously don't want to spam you, but here's another thought - the logic we should follow is 'one function = one purpose' (kind of the OOP philosophy, too). Splitting `convert()` we get
- one function doing 'take *one* script from `Binaries` + convert image with it'
- one function doing 'take *multiple* scripts from `Binaries` + convert image with it'

.. in a way, that's duplicate code (which is **not** dry). There's already a function taking care of 'take script, convert image with it'. Simply put, this is about modularity and loose coupling.

Therefore, creating different functions whose only purpose it is to call another function, except one time passing `true`, and the other time passing `false`, isn't dry either.

**Comment by rosell-dk** [comment]
I seriously don't want to spam you too :)
I'm very happy with the work you have done, and would hate to spoil a good teamwork by getting nitty-gritty about small stuff.

You wrote while I was writing. Here is my response to your second-latest reply:

True that it is more flexible. But there is no need for limiting to a set, which makes it bloat, and also makes usage less simple. If one limits it to a set, it is probably because one has not grasped that it is a bad idea to do so. Limiting to one has its use: Namely to test whether a specific converter works.

I'm considering what you write in your latest reply. I'm not yet sure if I agree or disagree

**Comment by S1SYPHOS** [comment]
‚One cannot simply spoil good teamwork‘ - discussing changes is butter on my bread :sunny:

**Comment by rosell-dk** [comment]
I doubt that my proposal breaks the DRY principle.

From Wikipedia:
"When the DRY principle is applied successfully, a modification of any single element of a system does not require a change in other logically unrelated elements [...] Besides using methods and subroutines in their code, Thomas and Hunt [...]"

From some other unreliable source:
"When you need to write new code which has similar (or the exact same) functionality to previous code already in the project you should take the logic (the previous code) and make it a generic callable sub routine, which can be used for multiple purposes.
This generic sub routine can cover all the use-cases via parameter values passed to it."
[http://mindfsck.net/dont-repeat-yourself/]

It seems that doing what I propose is exactly in the spirit of DRY.

But I do make sense in what you write. The one function = one purpose thing. Sounds like the single responsibility principle. Each class should have only one responsibility. 

Perhaps, I should have created the library in such a way, that the single converters could be used directly.... Well, now that I think of it, I actually did. Well, then I guess my need is fulfilled that way. Only I'd like the test that the destination file actually exists also to be done by the single converter. So I can rely on it. And actually that is where it belongs - the responsibility to convert and tell if it went okay must lie within the single converter (the responsibility of WebPConvert, I guess, is to provide a way of calling the converters in succession). We could put the "does destination file exist"-test in a super-class that the converters inherit. Perhaps in 1.1.0.

**Comment by rosell-dk** [comment]
Actually that would also mean that `createWritableFolder`, `isAllowedExtension` and `isValidTarget` should belong to a new base class for the single converters.

**Comment by S1SYPHOS** [comment]
I thought about that, too: Having a base Converter class which holds the basic tasks (which as of now are part of WebPConvert).

After all, this library should loop over all converters, maximizing chances of successful conversion. Users may choose order and specific subset of converters, but generally this should not be necessary.

**New proposal**: keeping implementation of setConverters, but outsourcing basic tasks to Converter base class.

**Comment by rosell-dk** [comment]
ahh. Perhaps I was too quick, when I said that my needs are fulfilled. I can instantiate the single converters directly. But I'd like to do it in a generic fashion. I'd like to ask WebPConfig for the available converters, and then be able to run that converter (based on its name id, ie 'ewww'). And I cannot do that (easily) by creating instances of the single converters directly. It would be a drag. 

So perhaps I'd like a `convertWithSingleConverter(converterId)` method after all. And it doesn't go against the purpose of `WebPConvert`, if stated as "to provide a generic interface for handling the converters"

**Comment by S1SYPHOS** [comment]
.. but why repeat common tasks for every converter?

**Comment by rosell-dk** [comment]
Oh, I thought that we were on level here. Do you propose to add let `WebPConvert` inherit a base class? Well, no need, is there? - there would be no other classes than WebPConvert that would be going to inherit it.

The reason for having the base class on the single converters is a separation of concerns. The consern of a converter is to convert a file and report if it is able to do that or not. But right now, part of that concern is maintained by WebPConvert, which for instance checks if target file exists. But this is none of its business. `WebPConvert` business is to provide uniformed access to converters and to make themwork in tandem. 
As I propose to hand these common tasks over to a base class, they are not be repeated in a bad way.

**Comment by rosell-dk** [comment]
I want to be able to do the things I could do with the library before the rewrite. I want for example to show in plain text the flow of the conversion. And I don't want such a small request to become a huge deal. It will not take anything away from the ease of use of the library that it allows more than its primary function.
The proposed base class was refactoring for the sake of separation of concerns. It does not even have to change the API. I remember that I thought about doing it, when I created the library. But I didn't remember why I did not do it. But I think I know now. If for example the target file doesn't exist, then it makes sense exit early with that message. There is no need to loop through all converters - they will predictively fail. So while separation of concerns would dictate that the converters took the complete concern of converting and detecting errors, it is not practical in this case.

I think it is time to move on.

For 1.0.0, we can use your solution with `setConverters($array, $exclude = false)`. But I will rename it. Probably I will go for `setPreferredConverters` or `setConverterOrder`. The primary use is to set order. This also allows for depreciating the exclude option later, if a better solution is discovered.

I will do the renaming after merging your patch, along with other modifications.

I see that you made a lot of methods public. Perhaps in order to make unit tests? But such concerns should not impact decisions about the API. Methods such as `isValidTarget`, `isAllowedExtension` and `createWritableFolder` clutters the public API. I also think we should make `getConverters` private to begin with. We can make it public later without breaking anything. But we cannot do the opposite. And having it public requires us to maintain the functionality, which limits our possibilities to change the inner workings.

**Comment by rosell-dk** [comment]
It is btw possible to unit test private methods with the reflection api. See here:
[https://jtreminio.com/2013/03/unit-testing-tutorial-part-3-testing-protected-private-methods-coverage-reports-and-crap/] (in the section "Targeting private/protected methods directly").

But I think it is enough to unit test the public methods for starters.
