### ISSUE TITLE
Some PNGs not showing on Safari or Edge

### ISSUE THREAD

**Issue by LeoRichard** [rosell-dk/webp-convert#183]
Hello, i got problems with PNGs in Safari, they are not showing, neither on Edge. Im using Cache enabler (already checked the webp cache option). The images which are not being converted to .webp are the ones that are shown in Safari. And on chrome those images that are shown on Safari, are not being converted to .webp on chrome.

Also on edge when opening the image itself it shows a weird code, not the image:

��WEBPVP8LI ��/ü����abÿ�uâ]Ïó\wwwwwwwwwwwwwwww÷{ÿvÝÝÝýþäœéÿy˜ëË!Íì „Ý„Iw“†.¡¤;ÒÕç�rVÍ�Ì®ùMÙ‘†Y2iØ��v„9ì&�–„“Ù�æÃn�é’æŸÙMJf7¥a×4‡DœÌl�þÕñý¿þÿ÷ÿõ?ü;�ëïÿ³ÿðxìOþð/ø¡ßí;›ÑÛ}ç�ð3�çÞã¬_øÙ{¬µ‘ÜZû13�7&rwþç.ýì Cõë?md£·¬�Y;ô�cÀ�Õ�<îNíA?Ó ãä�Ó¸5.Z[K�³ð‰ßëót'Â�œî0�;62îÚþ_z¬˜)M¸SéùÒì(W>¼5®ÛÒ¡ƒ¿œ�
YüÁ•Õ/¾òíÉ Z�ýé?¶š	ÓÕ›>™ÎŒúœ¨Ns´š¹9Zý¾å�Q0d�Cûæ5LTšÐûžxøe¾r˜g
àus�Ò|ï��ï*ùµñ(�¾”ø8!ýø�¡ð�[ã°™�íiªŒ}�I��[h?Åþ— ¬Ýö©O<TÌLìU�½Ø‰ÇŒöæælGhÙ�§oòg³htíGý‡z3Âb’þÓF“aøraü�Èº�?ÜÁz6d�¸h#g‡äJSÃØ5�^+É�¼F’/�–tFÖ°žc�Ø?k�+ãžNTJ:óH¾~E$yÂN&�Iz÷¥'�æ�:ØI$�‰ÔÝê(‘H$>hÌ�Z£lzr…ç5�ÆÎÆÂb–ü¼±Ò[�pÙ‰���îV��8�s� Ï,}ÊÚäädmÇJìäÎJÜ“E¥ô1»‚ü�ƒg�+å��OÖ‰�êw«ëB"Ö~½5bÓÔ§}Js=ÂÆû&Yù–%O0¶OgªÌWˆ7Jò�œ!™€!�ŒæåŽLÝßG�ðù#.�é�}}I3[ªWK�drÈ“œUUgF’�ž±$ÍŒGræ"In��×êsO6à©™y’õ™½ŽÐYItDrõè¶c‡¾ªgtâ�“Ìö7�1Q¼¢�+�2HfIf“Y’A2+0ØNå˜¬�Ar•d.™fÇ'(EÆ�¯›ä•ž¦çÙ¬bÜó<[_%�µ�ím�÷�;�ÅÈ�c.æÈ¯ºoŒ1%�cÌþÙ�Yó„µã’QkŒñ�ÈbÓ¸aö×ÈÛJêÇ%)ÉurÖs§Ùï3m…sZáÄöw.Æ^rôÊöÄªk¾†?Ñ·}�:ñOV¯TOúŽ‚Ûöõ�¥c �ëë; \ê�š�ä¸K&�0×#liTæ7 @á¹¶9Ñjµžÿ�ÉîJ«U™”mTZ­J†äÅJ«Õ:”ù_ñ%Ïå�Âz4æä�_}þ­V«R•�°þ¬ @áÚRZ§¼´7�à!>Ãþ²Ö•«‹y ¿xµÛ�ÛžhµZ­Õ"ÉÌÀb�xàƒ»Ûîy‡ä9·JY®:é¾ e”��Kr��â²a�X&Ù�€”¤ø"¡žê_ÕÊ�€h}ÙÖ=P®§TõE¨�/¨ÊW¡yª×Qr�â�É¥�”y/p¡*Ù&»]ò6Èr$ì(– ÐÜË�(‘¬ =2Oøú$_²P��/C·‘ÑjB�&%�.hvõÉ†�Ð�’ýúkÐÞ<é ×‚¸Dò�´']¸­d‡ zšîŒ‘)O8���)ÄÆÜ£o@� ÁS‡´ë!�ÈORg�âjN!6Rs�,–……�Ä©Å.IcVÈ=Wˆ�¹T^À³þëzû�#’éE��Kï½t£�D¡ ¿ÓFÆ�[&�vÜkjmxÆxÞ�é�5…ï,Û…ør¿ï�N§^rìœ†øü»{‹�®5v¨³Ð�¦ÓÔy¹Õô�Þ^�H¦/�ÀÜÖ¯�¦w�=�,VHž…x*“NgÎ��Ò�‚xÆ'y��zH²s$¢›¹Ó‚wŽd²Þ�ÑÆU“¥‹§Ï�’ìóŒ1&:’�
Â>E� VsÂ‰�I¦»©ÁÑ.�XŸ¦Î>E�@˜I’[�0s�âÍG
��dvD�¦´)
���yáùgI²&Ô�þaß�îXcŒñ–IÒÏÍFª�˜Ë…$yÛÈ�c¢‹«’-��
$L�ÆÈW�€©#êJžzq��ænRg$�°’�€�²%ôS>$Ü"¿3�¤²��º�WoN�ÀD’â²�ZùÙ!]¯JŒw! É�Ù�•~_dD;Ié°�QÙ�#%a•Î.?k�˜é£Ö<•žÐÃ � p¤8ù��ÌU8$ìSi„yÅùu��9¢´<�±ðÔ½îÐ¥ �	Æëi�ÓÙºìzV ~}ß�gd7e—„ ªå�Ù�N» 7ÔëV���X|ˆ�Fþº"·� pÄ¦°¥Ú�ö�ò-*W$âÞš;¬[‰1^3^²%ÁÄKRã5�4êÏÉZÂ‚ª/FN	K.¤�…®ï«WUÕ„3<*�x²¡"Ü�~6=aRuA�VŒÌ�—§�ÜZT ¿ãNo<’IeÎí6å§„�UÍA\6ìlXhºpmí��ÀHYkV5/4Yî�ðH+Šô�€©i–„Óª%Á*ÎÔ�<ÿœ‚�¸vjP‚‡xè �ì±³K9EI¸¥:åXvÃÙŠ°�:�c¿€„¯³«º!Œ3Ü�ÐèTt7�Œ…¼ ÜPÝ�&�	î
ˆ«HfSÍ��Ì»�œ¶:fÚ�ÈNPÙ)ä¿ªì;?pÕ�pMRm;Ë4�4j.„á%�ó:…”¬Þ���%=�¸�Jü��ì“Å�€ü²l-� p¤Q���³²�¥KÂ=îð¶6Òð¶Â°Ç‘ýªT�ƒ�ðH;…ï¼�Õh�@£F²øÔá,Ü�€™5!µ›Ôáô¢�ïÔÀJhw�À ŸÌä�? ™m�@>E2��s}Âö£�€Ujðû��æ¶BùÆŠdRðHú¾3vÛHešCËq'v+ÔàŠ€ü¥þ¥Ä�‡Æ_��€ÂÀŠ÷Há�—���O,ÍŸhãùgu¸œ�€G_Ô@áå.õ·��Ðè$É3�Ö£�;�ñ*IŽ�� ½º´”(�@!£Å��ç�2ù¬�ÖÁÉòW��vÈë�;‡ÎØ¶‘Ê4=ãÐžÍR÷¯ß�ô�Î ò¹†3�A��:,	x®�]–�àÐõ(þÎuAs½,pEÐ�¢žŸ�0À�âT�Ä¹2““§ÏÖ�gì´‘Êid·²Ôÿõ×4æv5‚óª—<��BO
kZ¹ç*ÀÈ¦V�¢ÆnNÂŸ}Më©ÿlÊûó:ùy:àï¼,+��ÈóuòèëGãk½.ðû–¬;Qt�Òir¸ »uÛY N·dg²5a™ä%!%�õMÕSÿªdïC�pYàÏî�pŽM�(v�È�ýYŸÊtÔ¥˜Šþ0Õk{ª½5J3Â	�Ýy!�…�6Uë $ÃÉúdÝwƒÓãÖ:‹lÿ(Ý¼9ŸØ{®û_ßgM‡~{¸¼·ÛIN/´Û ¿“du¡Ýn§eüë�öÄÞÞKŽ¯åHæ:Ûíö�Jo.´Ûí…nŽ-´Ûí,+çNíÝØÝ)S»¸qõüæù«�Ej‡ÝÑóßÜ¬Dk!åév»½�‘p{¡Ýn�TÉ¿Þ�µžúÄ­áÙ€b.s=¤»~fÈÚH'²öbg–ÇVï¾~HWÃ�1éûŒÉp¬v1²êøø÷ x¬ï§ÜoÌþìîúÖÆÆxmùæ�f �wÄúÿÌ›<¾«d®_Ïô�·ý¿§��

Im stuck on this, already cleared cache multiple times. Any ideas?

Config:

![image](https://user-images.githubusercontent.com/15838572/59234749-cc081780-8bb3-11e9-9e3f-5d940fa6e391.png)

![image](https://user-images.githubusercontent.com/15838572/59234763-d9250680-8bb3-11e9-85ac-df8bc4f7c9c3.png)

**Comment by LeoRichard** [comment]
Seems to be images were corrupted. They were encoded as WEBP but format was PNG. Website was migrated a few days ago, could be a migration problem?

I've been reuploading corrupted images and now everything seems fine. But still curious what could have caused that.

**Comment by rosell-dk** [comment]
Was it the *original* images that were corrupted? Encoded as WebP, you say? Very strange. By "format was PNG", do you mean that the file extension was PNG?

**Comment by rosell-dk** [comment]
I am investigating if it could be that WebP Express in some cases tells WebP Convert to store the destination at the source.

Btw: In the upcoming release, WebP Express stores a log file for each conversion, and it will be evident from the log files if that should happen.

**Comment by rosell-dk** [comment]
When the conversion is triggered by one of the conversion scripts (wod/webp-on-demand.php or wod/webp-realizer.php), the destination is calculated by lib/classes/ConvertHelperIndependent::getDestination(). I have inspected that method. In all branches, it will return something that ends with ".webp". So that part cannot be responsible for such failure

**Comment by rosell-dk** [comment]
When the conversion is triggered by Bulk Convert, `BulkConvert::processAjaxConvertFile()` is called, which in turn calls `Convert::convertFile()`. The destination is calculated by `Convert::getDestination()` which in turn calls `ConvertHelperIndependent::getDestination()`. And I just established that this cannot return the path to the source, as it always returns something that ends with ".webp"

**Comment by rosell-dk** [comment]
When new files are uploaded, I hook up on `wp_handle_upload` and `image_make_intermediate_size` (in *webp-express.php*). The hooks are implemented in `HandleUploadHooks::handleUpload()` and `HandleUploadHooks::handleMakeIntermediateSize`. Both of these calls `HandleUploadHooks::convertIf()`, which in turn calls `Convert::convertFile()`, which I just established ends up calling `ConvertHelperIndependent::getDestination()`. So this is fine too.

There are no more ways that conversions can be triggered.

**Comment by rosell-dk** [comment]
You mention *migration*. If the migration grabs the images through http (rather than copying the files), then yes, the migration is probably the problem. Upon migration you must turn off varied image responses. Or simply deactivate webp express before migrating.
