### ISSUE TITLE
ConversionFailed on server

### ISSUE THREAD

**Issue by ImKubass** [rosell-dk/webp-convert#202]
I am having issue using WebPConvert::convert on server. While I am on local server, it works fine. But while I upload it on server it throw bunch of errors.

Fatal error: Uncaught WebPConvert\Convert\Exceptions\ConversionFailed\ConverterNotOperationalException: None of the converters in the stack are operational in DISK2/www/3472/brilo.work/rolig/wp-content/themes/rolig/panda/vendor/rosell-dk/webp-convert/src/Convert/Converters/Stack.php:231
Stack trace: #0 /DISK2/www/3472/brilo.work/rolig/wp-content/themes/rolig/panda/vendor/rosell-dk/webp-convert/src/Convert/Converters/AbstractConverter.php(336): WebPConvert\Convert\Converters\Stack->doActualConvert() #1 /DISK2/www/3472/brilo.work/rolig/wp-content/themes/rolig/panda/vendor/rosell-dk/webp-convert/src/Convert/Converters/AbstractConverter.php(248): WebPConvert\Convert\Converters\AbstractConverter->runActualConvert() #2 /DISK2/www/3472/brilo.work/rolig/wp-content/themes/rolig/panda/vendor/rosell-dk/webp-convert/src/Convert/Converters/AbstractConverter.php(287): WebPConvert\Convert\Converters\AbstractConverter->doConvertImplementation() #3 /DISK2/www/3472/brilo.work/rolig/wp-content/themes/rolig/panda/vendor/rosell-dk/webp-conve in /DISK2/www/3472/brilo.work/rolig/wp-content/themes/rolig/panda/vendor/rosell-dk/webp-convert/src/Convert/Converters/Stack.php on line 231

GD extension is enabled

Any idea what is the issue here, what is missing? Kinda clueless

**Comment by rosell-dk** [comment]
It is not enough that Gd is enabled. It must also have been compiled with webp support.

Here is your starting point:
https://github.com/rosell-dk/webp-convert/wiki/Meeting-the-requirements-of-the-converters
