### ISSUE TITLE
Converter throws TargetNotFoundException if path or filename contains spaces

### ISSUE THREAD

**Issue by theDyingMountain** [rosell-dk/webp-convert#204]
Is it possible to allow spaces in path or filename? At the moment a TargetNotFoundException is thrown.

**Comment by rosell-dk** [comment]
Hm, can't reproduce.
The only place the TargetNotFoundException is thrown is in `src/Helpers/PathChecker.php::checkAbsolutePathAndExists`

That code says:

```php
    public static function checkAbsolutePathAndExists($absFilePath, $text = 'file')
    {
        if (empty($absFilePath)) {
            throw new TargetNotFoundException($text . ' argument missing');
        }
        self::checkAbsolutePath($absFilePath, $text);
        if (@!file_exists($absFilePath)) {
            throw new TargetNotFoundException($text . ' file was not found');
        }
        if (@is_dir($absFilePath)) {
            throw new InvalidInputException($text . ' is a directory');
        }
    }
```

So if it fails, it seems it must be because `file_exists` fails when the file contains a space. I haven't tested if that happens on some systems, but it does not happen on my dev server (PHP 7.3 fpm, Linux)

**Comment by theDyingMountain** [comment]
Yes, the exception is thrown in this helper function. The problem occurs on a shared hosting server with PHP 7.0 where all spaces are encoded with %20.  So maybe a solution is decoding the path with `rawurldecode `before calling `file_exists`?

**Comment by rosell-dk** [comment]
Hm, I would say that that responsibility lies with on code that calls `WebPConvert::convert`. Which context is it used in? Who does the call?

**Comment by theDyingMountain** [comment]
Hm, I think you right. I'm using your lib for a webp conversion [symfony bundle für CMS Contao](https://github.com/postyou/contao-webp-bundle). I will do the decoding before calling `WebPConvert::convert`

**Comment by rosell-dk** [comment]
Oh, so you have made an extension for Contao using WebP Convert. Thats great :+1: I shall add a link to it from the README.

I see that you are using WebP Convert version 1. I shall recommend version 2. There are many improvements in the conversion methods (they support more options) and there is a new conversion method "Vips". 

I have written this document about migrating to version 2:
https://github.com/rosell-dk/webp-convert/blob/master/docs/v2.0/migrating-to-2.0.md

**Comment by theDyingMountain** [comment]
Thx for the tip, I upgrade my extension to version 2 and add some new features.
It would be very nice, if you can link the extension in your README.
