### ISSUE TITLE
Set up Travis CI (without errors)

### ISSUE THREAD

**Issue by rosell-dk** [rosell-dk/webp-convert#21]
We are getting there.
I have activated the service.

https://travis-ci.org/rosell-dk/webp-convert/jobs/364995727

Right now it errors out. The reason is that phpunit requires php 5.6.
I'm updating the travis config file to not test php 5.5...

**Comment by rosell-dk** [comment]
Yes. That helped

**Comment by rosell-dk** [comment]
Oh. It fails in hhvm.
Error: "friendsofphp/php-cs-fixer v2.11.0 conflicts with hhvm[3.25.2]
 
Will you look at it, @S1SYPHOS ?

**Comment by rosell-dk** [comment]
I, btw added a build badge [https://github.com/dwyl/repo-badges]

**Comment by daybugging** [comment]
See [this](https://hhvm.com/blog/2017/09/18/the-future-of-hhvm.html) and [this](https://www.reddit.com/r/PHP/comments/70wtky/the_future_of_hhvm/), just drop HHVM and you'll be fine!

**Comment by rosell-dk** [comment]
You beat me to it :) Was just about to push

**Comment by S1SYPHOS** [comment]
All builds passing now!
