### ISSUE TITLE
Quality is different from the original

### ISSUE THREAD

**Issue by thanhansoft** [rosell-dk/webp-convert#214]
Hi Admin,

I use the GD image processing library. But the image is a bit pale compared to the original
This is code:

`<?php 
require_once 'vendor/autoload.php';
use WebPConvert\WebPConvert;

$source = __DIR__ . '/video.jpg';
$destination = __DIR__ . '/video-optimizer.webp';

$success = WebPConvert::convert($source, $destination, [
	// It is not required that you set any options - all have sensible defaults.
	// We set some, for the sake of the example.
	'quality' => 100,
	// 'max-quality' => 100,
	'converters' => [ 'gd'],  // Specify conversion methods to use, and their order
]);`

Please see comparison image https://www.photobox.co.uk/my/photo/full?photo_id=502128321240

Please download code and two image: http://www.mediafire.com/file/97e7rltdawb1f0k/v9.zip/file

I want the image to be the same color as the original. help me

**Comment by rosell-dk** [comment]
Yes, I can see that. And it in fact doesn't only happen with Gd. I tested all the conversion methods and the image gets pale in all of them (gd, cwebp, vips, imagick, imagemagick, graphicsmagick, gmagick and ewww).

When I open the image in GIMP, GIMP tells me that the image has an *embedded color profile*. It asked me if I'd like to convert it to usual RGB. I said yes. When I convert the resulting jpeg, the colors looks like the original.

**Comment by rosell-dk** [comment]
Here is the jpeg with usual RGB color profile: https://ibb.co/v1SnKDY

**Comment by thanhansoft** [comment]
Hi rosell?
Please tell me what GIMP is, I don't understand

**Comment by rosell-dk** [comment]
[GIMP](https://www.gimp.org/) is an image editor. But you do not need it unless you have other JPEG images which has the same problems. Do you?

**Comment by rosell-dk** [comment]
I provided a link to the jpeg which you can use instead

**Comment by rosell-dk** [comment]
Here is a link to the webp: https://ibb.co/gyYW62D

**Comment by thanhansoft** [comment]
ok, thanks for support. good health
