### ISSUE TITLE
webp-on-demand does not redirecting me to image

### ISSUE THREAD

**Issue by sashabeep** [rosell-dk/webp-convert#215]
in my htaccess:
```
<IfModule mod_rewrite.c>
    RewriteEngine On
    # Redirect images to webp-on-demand.php (if browser supports webp)
    RewriteCond %{HTTP_ACCEPT} image/webp
    RewriteRule ^(.*)\.(jpe?g|png)$ webp-on-demand.php?source=%{SCRIPT_FILENAME} [NC,L]
</IfModule>

AddType image/webp .webp
```
When i try to open any .jpg file hothing happens with on-the-fly conversion, just jpg displays. But when i call
/webp-on-demand.php?source=my/jpg/file.jpg
script is reporting that
```
...
gd succeeded :)

Converted image in 36 ms, reducing file size with 22% (went from 16 kb to 13 kb)
```
and creates my/jpg/file.jpg.webp alongside with original one

Why are redirect to conversion and created image doesn't work?
I'm using lite speed web server
The other rewrite rules in .htaccess works as expected. What am i missing?

**Comment by sashabeep** [comment]
UPD: Moved redirect rule at the top of .htaccess file and conversiopn seems to be ok but i'm getting reports instead of images despite the 'show-report' option is set true or false or commented

![Снимок экрана 2019-09-09 в 23 20 26](https://user-images.githubusercontent.com/5689796/64563649-872d8180-d358-11e9-9228-5a6518096bdc.png)

**Comment by rosell-dk** [comment]
0.15.0 is out.
Can you tell me if it works now?

**Comment by rosell-dk** [comment]
Can you paste in the output after pressing the "Live test" button ?
Perhaps you simply need to change some file permissions.

**Comment by sashabeep** [comment]
Hmmm... 
```
Fatal error: Uncaught Error: Call to undefined method WebPConvert\WebPConvert::convertAndServe() in /****/webp-on-demand.php:16 Stack trace: #0 {main} thrown in /****/webp-on-demand.php on line 16
```

**Comment by sashabeep** [comment]
Installed using composer

**Comment by sashabeep** [comment]
webp-on-demand.php
```php
<?php
require 'vendor/autoload.php';        // Make sure to point this correctly

use WebPConvert\WebPConvert;

$source = $_GET['source'];            // Absolute file path to source file. Comes from the .htaccess
$destination = $source . '.webp';     // Store the converted images besides the original images (other options are available!)

$options = [

    // UNCOMMENT NEXT LINE, WHEN YOU ARE UP AND RUNNING!    
    'show-report' => false             // Show a conversion report instead of serving the converted image.

    // More options available!
];
WebPConvert::convertAndServe($source, $destination, $options);
```

**Comment by rosell-dk** [comment]
Sorry, ignore my last comment. I thought you were using the Wordpress plugin. There is of course no "test" buttons in this library...

**Comment by rosell-dk** [comment]
The problem was perhaps simply that you were using the tutorial for 1.3 but using WebPConvert 2.0. The "convertAndServe" method was renamed to "serveConverted" in 2.0.
