### ISSUE TITLE
Ewww API key

### ISSUE THREAD

**Issue by S1SYPHOS** [rosell-dk/webp-convert#23]
Check out this [commit](https://github.com/nosilver4u/ewww-image-optimizer/commit/d2bfd9637d52b4e1708f6dae80ceb4490d6161bd) in ewwwio plugin, regarding invalid API keys, maybe that’s interesting for us, too

**Comment by rosell-dk** [comment]
That commit did not do anything regarding API keys. However, as our ewww converter works fine, there is no reason to dig into it now. But nice to know that ewww is on github.
