### ISSUE TITLE
Add converter based on ffmpeg

### ISSUE THREAD

**Issue by rosell-dk** [rosell-dk/webp-convert#232]
As mentioned [here](https://winaero.com/blog/convert-webp-png-linux/), it is possible to convert images to webp using ffmpeg. He mentions that it may be more widely available than cwebp.

Here are options:
https://www.ffmpeg.org/ffmpeg-codecs.html#libwebp

**Comment by rosell-dk** [comment]
I tried it out. 
It seems I cannot get it to respect the options.
The following all generates webp images with the same size:
`
ffmpeg -i small.jpg small-test.webp -compression_level 6
ffmpeg -i small.jpg small-test.webp -compression_level 0
ffmpeg -i small.jpg small-test.webp -lossless 1
ffmpeg -i small.jpg small-test.webp -lossless 0
`

**Comment by brendan8c** [comment]
> I tried it out.
> It seems I cannot get it to respect the options.
> The following all generates webp images with the same size:
> 
> ```
> ffmpeg -i small.jpg small-test.webp -compression_level 6
> ffmpeg -i small.jpg small-test.webp -compression_level 0
> ffmpeg -i small.jpg small-test.webp -lossless 1
> ffmpeg -i small.jpg small-test.webp -lossless 0
> ```
--------------------------------------------------------------------------------------
Use this filter to reduce file size.
lossless Enables/Disables use of lossless mode. Default is 0.
qscale For lossy encoding, this controls image quality, 0 to 100. The default value is 75.

ffmpeg -i small.jpg -lossless 0 -qscale 10 small-test.webp

**Comment by rosell-dk** [comment]
Found the problem. The options must be specified before the output file

**Comment by rosell-dk** [comment]
Closed in #8e46667
