### ISSUE TITLE
Feature request: make redirects independent of server name

### ISSUE THREAD

**Issue by TimVevida** [rosell-dk/webp-convert#236]
Hi there,

We have a setup where the contents of the acceptance site are copied to the live site. With the `.htaccess` rules containing the server name of the acceptance site, the live site breaks.

This is easily remedied by replacing the current site url in the `.htaccess` rules with `%{SERVER_NAME}`. Would you consider this?

Otherwise, our live site will break the next time the `.htaccess` rules need to be updated. :)

**Comment by rosell-dk** [comment]
Are you using [WebP Express](https://github.com/rosell-dk/webp-express/issues/)? (this is the *webp-convert* repo)

**Comment by rosell-dk** [comment]
I'm confused. I don't believe that the site url is used in the .htaccess rules?
Can you copy the .htaccess rules here, so I can inspect?

**Comment by rosell-dk** [comment]
And oh - please create a [new issue in WebP Express](https://github.com/rosell-dk/webp-express/issues/new) (I'm assuming that this is WebP Express related, although there are other plugins that uses webp-convert). I'm closing this

**Comment by TimVevida** [comment]
Yeah, I meant WebP Express. Sorry about that. I will create an issue there.
