### ISSUE TITLE
Warn users on older versions of Gd, that it looses the alpha channel

### ISSUE THREAD

**Issue by rosell-dk** [rosell-dk/webp-convert#238]
Old versions of Gd does not handle transparency (in some PNGs)
Experienced in GD Version: 2.1.1-dev.

Reported here: https://github.com/rosell-dk/webp-express/issues/374

**Comment by rosell-dk** [comment]
There is hope. Perhaps the solution is [here](https://github.com/claviska/SimpleImage/issues/28) or [here](https://stackoverflow.com/questions/2611852/imagecreatefrompng-makes-a-black-background-instead-of-transparent).

**Comment by rosell-dk** [comment]
Here is a link to knowledge on the PNG format. http://www.libpng.org/pub/png/book/chapter08.html

**Comment by rosell-dk** [comment]
Gd 2.2.5 has no problems. I do not know about the versions between 2.1.1-dev and 2.2.5. Please contribute!

**Comment by rosell-dk** [comment]
Also reported on 2.1.1.

**Comment by rosell-dk** [comment]
For those that experiences this, here are your options:

- Disable PNG. Gd isn't very good at converting PNG anyway, as Gd cannot create lossless webp, only lossy webp
- Ask your host to upgrade Gd
- Ask your host to install imagick, vips or cwebp
- Use a cloud converter (ewww or connect to a remote webp-express / wpc)

**Comment by ve3** [comment]
To be more specific, this GD's problem occur on PHP older than 7.0. It means PHP 5.6 or older.
