### ISSUE TITLE
Should WebPConvert::convert return boolean or not?

### ISSUE THREAD

**Issue by rosell-dk** [rosell-dk/webp-convert#24]
We decided to start throwing exceptions.

Convert can now throw the following exceptions:
`TargetNotFoundException`
`InvalidFileExtensionException`
`CreateDestinationFolderException`
`CreateDestinationFileException`
`NoOperationalConvertersException`

We removed the return value. The reasoning was that it felt a bit too much if the convert could fail in two different ways (both by throwing exceptions and by returning false)

And the usage example was updated to recommend wrapping the convert call in try-catch statement.

Now I realize that it perhaps was a bad decision.

The first two exceptions (`TargetNotFoundException` and `InvalidFileExtensionException`) truly calls for exceptions to be thrown. If that happens, there is probably a bug somewhere.

The next two (`CreateDestinationFolderException` and `CreateDestinationFileException`) are perhaps also rightly thrown as exceptions. The problem is probably one of setting the right file permissions. So it is probably not a code bug, but problems with the server setup. I'm not sure if such problems are rightly handled with exceptions.

The last one are perhaps wrongly thrown. It is certainly not a programming bug, if no converters can handle it. It could be argued though, that it is problems with the server setup, and therefore should be treated in a similar way as above, ie also by throwing an exception.

I lean towards keeping all exceptions, but the last. Instead of throwing a `NoOperationalConvertersException` exception, it seems more right to simply return false. 

Comments and arguments are very welcome!

**Comment by S1SYPHOS** [comment]
I was always and still am in favor of my approach :)

**Comment by rosell-dk** [comment]
meaning?

**Comment by rosell-dk** [comment]
Ok, so you agree with what I am leaning towards. I'll implement it then. But keep the question open a bit, to allow others to comment

**Comment by rosell-dk** [comment]
I'm btw in the process of updating the converters to throw either a `ConverterNotOperationalException` or a `ConverterFailedException`. `ConverterNotOperationalException` means that some general requirement is not met. `ConverterFailedException` means that something went wrong, even though general requirements seemed to be met. So it is probably a problem specific to that single conversion.

This allows us to distinguiish between two different situations. One situation being that conversion could not be made, because no converters are operational. This should return false, then. The other situation is that no converters are able to do the conversion, and at least one converter failed even though its general requirements seemed to be met. In that case, I believe it is right to throw an exception.

See also #20, where I argue that no failure in a single converter should result in WebPConvert giving up totally. That would be against the general purpose of WebPConvert, which is to try as hard as it can to make a conversion.
