### ISSUE TITLE
Access level to WarningLoggerTrait::logLn() must be public

### ISSUE THREAD

**Issue by sizeg** [rosell-dk/webp-convert#243]
Hi, I've get this error after upgrade to PHP 7.4. It's easy to reproduce https://3v4l.org/NhXm9

> PHP Fatal error:  Access level to WebPConvert\Convert\Converters\BaseTraits\WarningLoggerTrait::logLn() must be public (as in class WebPConvert\Convert\Converters\BaseTraits\OptionsTrait) in /var/www/vendor/rosell-dk/webp-convert/src/Convert/Converters/AbstractConverter.php on line 17

```php
<?php

trait OptionsTrait {
    abstract public function logLn($msg, $style = '');
}
trait WarningLoggerTrait {
    abstract protected function logLn($msg, $style = '');
}
class AbstractConverter {
    use OptionsTrait;
    use WarningLoggerTrait;
}
```

https://github.com/rosell-dk/webp-convert/pull/244

**Comment by sizeg** [comment]
https://github.com/rosell-dk/webp-convert/pull/244

**Comment by rosell-dk** [comment]
Thanks, btw!

**Comment by rosell-dk** [comment]
I have released it. And WebP Express has just been updated too, to use this fix
