### ISSUE TITLE
None of the converters in the stack are operational

### ISSUE THREAD

**Issue by nhockool1002** [rosell-dk/webp-convert#252]
I have a small issue "None of the converters in the stack are operational" when I upload picture
My function is
`
$fileName = $request->file('image')->getClientOriginalName();
$request->file('image')->move(public_path('uploads'), $fileName);
 $source = public_path('uploads') . '/' . $fileName; 
$destination = substr($fileName, 0, -4) . '.webp';
WebPConvert::convert($source, $destination, []);
`
$ource : /var/www/html/public/uploads/272885.jpg
$destination : 272885.webp

**Comment by rosell-dk** [comment]
Check out the following entries on the wiki:
https://github.com/rosell-dk/webp-convert/wiki/Meeting-the-requirements-of-the-converters
https://github.com/rosell-dk/webp-convert/wiki/A-PHP-script-for-the-webhost
