### ISSUE TITLE
Segmentation fault when reaching 1765 processed images

### ISSUE THREAD

**Issue by xplainit** [rosell-dk/webp-convert#257]
We have this issue, we are processing a big library of images, from JPG / PNG to WEBP. We are using the implementation from the examples and we are processing the images in a prestashop installation (prestashop version 1.7.6).
Every time we run the script and using the library, we get a segmentation fault after the first 1765 images have been processed.
Example: We run the script on the entire library, it processes the first 1766 images and crashes with a segmentation fault.
Second pass, we get new 1765 images converted (checked with find filetype command). On the third run we have a total of 5296 images, which means that on the third run, it also processed 1765 images.
Tested on CentOS 7 - 2 different servers - one is with 32GB RAM and other is 64GB RAM.
<img width="1273" alt="Indsat grafik-4" src="https://user-images.githubusercontent.com/8671640/93785524-77fd3700-fc2e-11ea-8483-b5a56b4129fe.png">

**Comment by rosell-dk** [comment]
Do you know anything about the "klconverttowebp" module? Does it allow configuring webp-convert?

**Comment by rosell-dk** [comment]
I can tell from the screendump that you are not using the latest version of webp-convert. Webp-convert now uses "cwebp-110-linux-x86-64" and I think I got rid of the "Access denied" warnings too. Try updating to latest version of webp-convert

**Comment by rosell-dk** [comment]
Any news on this?
