### ISSUE TITLE
Not working on Bluehost and Namecheap

### ISSUE THREAD

**Issue by rawadymario** [rosell-dk/webp-convert#260]
I tested this Library on my local machine, and it is working perfectly.
But on my servers (bluehost, and namecheap), when I call the function I am getting a 500 error.

I contacted support, and they told me that GD webp extension is enabled, but I can't figure out why the servers are breaking when I call the functions.

Anyone here faced/is facing such a problem?

**Comment by rosell-dk** [comment]
Have you tried this?
https://github.com/rosell-dk/webp-convert/wiki/A-PHP-script-for-the-webhost
