### ISSUE TITLE
Not works in php8

### ISSUE THREAD

**Issue by rickfleen** [rosell-dk/webp-convert#265]
When I run composer update:

Problem 1
    - Root composer.json requires rosell-dk/webp-convert ^2.4 -> satisfiable by rosell-dk/webp-convert[2.4.0].
    - rosell-dk/webp-convert 2.4.0 requires php ^5.6 | ^7.0 -> your php version (8.0.2) does not satisfy that requirement.

**Comment by ceesvanegmond** [comment]
Having the same issue. Would love to see this fixed ❤️

**Comment by lobodol** [comment]
Hi there,

Do you plan to make this library php8-ready soon?

Regards,

**Comment by nlxdodge** [comment]
Please us the 👍 on the first comment to show interests in this feature.
I myself made an automatic webp converter for all assets in my portfolio, but I switched to PHP 8.0+ and the images didn't work anymore. This is also the issue I am experiencing.

**Comment by rosell-dk** [comment]
I think its php8-ready now. I at least fixed issues found in test cases and phpstan. I shall release soon.

**Comment by rosell-dk** [comment]
Btw: I updated to newer version of PHPUnit (9.3). But that requires PHP 7.3. So currently (in master), you will need at least PHP 7.2. I'm not sure how to best deal with this, bit I will create an extra composer file ("composer-php72.json") which can be used instead.

**Comment by rosell-dk** [comment]
Fixed
