### ISSUE TITLE
Adding custom converters

### ISSUE THREAD

**Issue by rosell-dk** [rosell-dk/webp-convert#28]
It is not optimal that custom converters needs to be added to a specific directory, and needs to have a specific class name.

It is no great priority, but at some point we should create an `addCustomConverter` method that accepts a class

**Comment by S1SYPHOS** [comment]
What's the point using this library if you want to extend it without staying within its legitimate boundaries? Converter scripts go into `Converters`, that#s where they belong, and it's not asked too much to name file & class after the used converter / technique.

**Comment by S1SYPHOS** [comment]
And also that's easy by enforcing certain decisions be made - like having a class `convert()` that's responsible for conversion itself. We can easily achieve this by adding an `abstract protected function convert()` to the `Converter` base class.

**Comment by rosell-dk** [comment]
Wont fix, unless somebody needs it
