### ISSUE TITLE
Discard the $quality and $stripMetadata arguments, and replace with general $options array

### ISSUE THREAD

**Issue by rosell-dk** [rosell-dk/webp-convert#31]
This allows more options to be set, and makes the signature simpler

**Comment by daybugging** [comment]
I find it highly legitimate to keep those two out of a more general options array.
Firstly, they are the only options needed more often than not, secondly, they are by default not necessary, so if you just want basic conversion with sensible defaults, you may pass source & destination, that's it!

Moreover, it adds to overall complexity, when you have to set basic options in an array .. I'd guess only a minority of people using this library is even remotely interested in anything other than quality, stripping & actual conversion ..

**Comment by rosell-dk** [comment]
Stripping doesn't work with most converters anyway. So it is sensible to remove that option. Also, the cwebp library, that is the one that also do the work in Gd and Imagick, actually doesn't have that option. It has a 'metadata' option. I think it is a good idea mapping directly to cwebp options.

It is true that quality is an option needed more often than not. But I don't think named arrays adds to complexity. Named arrays are in a way self-documenting. Also, it is easier to see how to add new options - same system for all!

You write that the two options are special in the way that they are not necessary per default. But its not like that. It is so with all options actually. If you read the updated README, you will see. And all have sensible default values, of course.

**Comment by daybugging** [comment]
Alright than, I'm satisfied :man_dancing:

**Comment by rosell-dk** [comment]
:beers:
