### ISSUE TITLE
threat found on windows defender 

### ISSUE THREAD

**Issue by jarooghe** [rosell-dk/webp-convert#325]
windows defender says : 
![test](https://user-images.githubusercontent.com/23148584/145010515-634411b4-5550-4948-85d6-09fed58beba5.png)

**Comment by rosell-dk** [comment]
Hm.
The file is completely innocent. So it is a false positive.
But I can remove the file to avoid the false positive

**Comment by rosell-dk** [comment]
It is probably the part of the file where I quote some PHP found for using passthru for emulating exec(). I guess this type of code is usuable for creating backdoors. I will just remove that

**Comment by rosell-dk** [comment]
I removed the file in the [exec-with-fallback](https://github.com/rosell-dk/exec-with-fallback) library and created a new release for that library. Composer update should get you version 1.1.1 of exec-with-fallback.

**Comment by rosell-dk** [comment]
@jarooghe: It is fixed. Thanks for notifying me!
