### ISSUE TITLE
Notice: Undefined offset: 1 if WEBPCONVERT_CWEBP_PATH set

### ISSUE THREAD

**Issue by ssstankiewicz** [rosell-dk/webp-convert#326]
Hi,

If we set env variable WEBPCONVERT_CWEBP_PATH it's return error: 
Notice: Undefined offset: 1 in vendor/rosell-dk/webp-convert/src/Convert/Converters/Cwebp.php on line 858

I tried on 2.6 and 2.9 versions

**Comment by rosell-dk** [comment]
Yes, I can reproduce

**Comment by rosell-dk** [comment]
Thanks, @ssstankiewicz. It is fixed and released

**Comment by ssstankiewicz** [comment]
It's working. Thank you
