### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by S1SYPHOS** [rosell-dk/webp-convert#34]
Hey there,
off the top of my head, I guess using this library oftentimes will include batch conversion, and just in case images are re-submitted that didn't change, creating them again costs time.

So the idea would be to use some simple memoization functionality to cache each passed string of source, destination & options, so when a matching request is made, conversion of this particular image may be skipped - I don't know if you are making sense of this ..

**Comment by rosell-dk** [comment]
I'm not too worried about batch conversion. I guess such a thing will not be done without user being aware.

I'm not too worried about re-conversions either.

But what I *am* worried about is this scenario: #38

**Comment by rosell-dk** [comment]
As to caching, I'd reckon its outside the scope of `webp-convert`. At least for now. If the caching idea is to be pursued, I suggest it to be implemented in its own library, which builds on WebPConvert.

**Comment by S1SYPHOS** [comment]
True. It's the app using WebPConvert (and passing certain arguments) 
that should wrap the function call in some kind of caching mechanism.
You have chosen .. wisely!
