### ISSUE TITLE
Add coverage (like clover)

### ISSUE THREAD

**Issue by daybugging** [rosell-dk/webp-convert#40]

**Comment by S1SYPHOS** [comment]
Coverage reports are something I thought about, too, but to be honest, 
at this stage - as webp-convert is still a rather small library - it 
adds overhead we don't really need.

But, as always, I'm open for discussion and of course, PRs are always 
welcome!

**Comment by rosell-dk** [comment]
Maybe on some shiny day... (or perhaps, rather, on a rainy day)... Closing, as it will not be in near future
