### ISSUE TITLE
Publish on WP.org

### ISSUE THREAD

**Issue by pfefferle** [rosell-dk/webp-convert#48]
It would be nice to have it on WP.org to be able auto update the plugin.

Or at least composer support.

**Comment by rosell-dk** [comment]
Yes, definitely!

I'm working towards publishing it on WP, hoping to get it ready in a week or so

**Comment by rosell-dk** [comment]
I simply want to test it some more, before publishing.

**Comment by rosell-dk** [comment]
Ehm, this ticket belongs to the Wordpress version of WebPConvert...
https://github.com/rosell-dk/webp-express

**Comment by rosell-dk** [comment]
Just created the issue in WebPExpress:
https://github.com/rosell-dk/webp-express/issues/2

**Comment by pfefferle** [comment]
oops, thanks :)
