### ISSUE TITLE
Error Method not found

### ISSUE THREAD

**Issue by Back-Sephiroth** [rosell-dk/webp-convert#52]
When i call 

`
 WebPConvert::convert($file, 'mynewfile.webp', []); 
`

I have this error 

> Call to undefined method WebPConvert\Converters\Imagick::getImageCompressionQuality()

**Comment by rosell-dk** [comment]
Ok, interesting. It would seem that it is possible to have Imagick installed but not have access to that method. The fix will simply be to test that the method exists before calling it. Unfortunately, Im away from computer the nect three weeks. Perhaps @s1syphos can fix it?

Could you provide some details? What version og imagick are you using. Php version?

**Comment by rosell-dk** [comment]
(to find the relevant place to correct, simply search for the text "getImageCom" in all files... you guys now that)

**Comment by rosell-dk** [comment]
A Pull request will be appreciated. Im away from computer, but not away from browser, so I can easily accept a PR and create a new bug release, if someone would be kind enough to fix the little bug and submit a PR. Thanks!

**Comment by rosell-dk** [comment]
Until solved, you can set qualty explicitly:

`
 WebPConvert::convert($file, 'mynewfile.webp', ['quality'=>75]); 
`

**Comment by rosell-dk** [comment]
I guess the following code: (src/Converters/ConverterHelper.php)
```
        if (extension_loaded('imagick') && class_exists('Imagick')) {
            $img = new Imagick($filename);
            return $img->getImageCompressionQuality();
        }
```
Should be changed to:
```
        if (extension_loaded('imagick') && class_exists('Imagick')) {
            $img = new Imagick($filename);
            if (method_exists($img, 'getImageCompressionQuality')) {
                return $img->getImageCompressionQuality();
            }
        }
```
