### ISSUE TITLE
Append "v" before version number ?

### ISSUE THREAD

**Issue by rosell-dk** [rosell-dk/webp-convert#7]
The current version number is '0.1.0'. Should we instead have used 'v0.1.0' ?

I am undecided.

From the discussion [here](https://stackoverflow.com/questions/2006265/is-there-a-standard-naming-convention-for-git-tags), it seems that both formats are valid and that recommendations goes both ways.

It seems that appending "v" is most widespread. Using "v" also appears in many guides, for example here: https://help.github.com/articles/about-releases/

**Comment by S1SYPHOS** [comment]
I always choose to append it in the version title, but not the tag itself.

Angular doesn‘t use it for any of those two, React for both. Totally up to you, I say!

**Comment by rosell-dk** [comment]
Let's stay with what we have
