### ISSUE TITLE
Extend SPL exceptions, and restructure

### ISSUE THREAD

**Issue by rosell-dk** [rosell-dk/webp-convert#82]
Follow guidelines in these articles:
http://ralphschindler.com/2010/09/15/exception-best-practices-in-php-5-3
https://www.alainschlesser.com/structuring-php-exceptions/

Also, with the new Stack converter, there is no reason to have exceptions in two different namespaces

**Comment by rosell-dk** [comment]
I'm not sure which SPL exception I should extend when an extension isn't installed. For example, when imagick extension isn't installed. And what kind of exception is it, if it doesn't support webp?

I have been peeking around in other libraries. Basically, there are no satisfying answers to be found there:

In [Intervention/Image](https://github.com/Intervention/image), they throw their own "MissingDependencyException" when Imagick insn't installed. And they throw "NotSupportedException", when webp format isn't supported. Both extends their own "ImageException", which extends \RunTimeException

[avalanche123/Imagine](https://github.com/avalanche123/Imagine) throws *InvalidArgumentException*, when trying to save unsupported format. webp is implemented as a supported format (in Gd). If it fails calling imagewebp, a *RuntimeException* is thrown.

[Imanee](https://packagist.org/packages/imanee/imanee) Throws ExtensionNotFoundException if neither Gd nor Imagick extension is found. It extends Exception. Or it throws UnsupportedFormatException, which also simply extends Exception.

[PHPixie/Image](https://github.com/PHPixie/Image) doesn't check if extensions are available.


Btw:  *Intervention/Image* has added the following in composer.json. Perhaps a good idea?

"suggest": {
        "ext-gd": "to use GD library based image processing.",
        "ext-imagick": "to use Imagick based image processing."
}

**Comment by rosell-dk** [comment]
https://stackoverflow.com/questions/5245453/which-spl-exception-should-i-use-when-validating-set-data-before-a-process

**Comment by rosell-dk** [comment]
Gordon here is probably right:
https://stackoverflow.com/questions/14171714/php-runtime-or-logic-exception

**Comment by mrbig00** [comment]
> https://www.alainschlesser.com/structuring-php-exceptions/
A runtime exception, however, is an error condition that you have no control over during development. A database connection getting blocked by the firewall, a file permission that is incorrect, etc… These errors are unavoidable. You can not “develop a system where the database cannot fail”. What you can do is “develop a system where a failed database connection produces a nice error message and alerts the system administrators, instead of throwing a fatal error”.

I think that the best practice should be to create a base exception for the requirements, like WebpConvertException\RequirementException and extend from runtime exception.

**Comment by rosell-dk** [comment]
Implemented in latest commit (73d6a31)

**Comment by rosell-dk** [comment]
I choose not to extend runtime exception - as I agreed with [Gordon](https://stackoverflow.com/questions/14171714/php-runtime-or-logic-exception) - but I have organized the exceptions into a hierarchy)
