### ISSUE TITLE
Perhaps use rmccue/requests instead of Curl ?

### ISSUE THREAD

**Issue by rosell-dk** [rosell-dk/webp-convert#84]
rmccue/requests is able to use sockets directly when curl is unavailable

https://packagist.org/packages/rmccue/requests

**Comment by rosell-dk** [comment]
Not so sure. I stumbled upon the [virtual package](https://devedge.wordpress.com/2014/09/27/composer-and-virtual-packages/), php-http/client-implementation (I saw it used in https://packagist.org/packages/nexmo/client). 

I then ran into this:
https://www.sitepoint.com/breaking-free-from-guzzle5-with-php-http-and-httplug/

And this:
https://www.php-fig.org/psr/psr-18/

And then [Buzz](https://github.com/kriswallsmith/Buzz), which I see is maintained by Tobias Nyholm, who is also behind PSR 18. I guess Buzz is worth looking into...

**Comment by bologer** [comment]
@rosell-dk  I suggest Guzzle though

**Comment by rosell-dk** [comment]
Closing because this is low priority, but keeping track of it in 187
