### ISSUE TITLE
cwebp error X-WebP-Convert-Status: Failed (No converters could convert the image)

### ISSUE THREAD

**Issue by Skorefin** [rosell-dk/webp-convert#85]
Here is default webp-on-demand.php;
<?php
require 'vendor/autoload.php';
use WebPConvert\WebPConvert;

$source = $_GET['source'];
$destination = $source . '.webp';

$success = WebPConvert::convertAndServe($source, $destination, [
    'fail' => 'original',
    'quality' => 'auto',
    'max-quality' => 80,
    'converters' => ['cwebp', 'gd', 'imagick', 'wpc', 'ewww'],
    'converter-options' => [
		'cwebp',
        'ewww' => [
            'key' => 'your-api-key-here'
        ],
        'wpc' => [
            'api-version' => 1,
            'url' => 'https://example.com/wpc.php',
            'api-key' => 'my dog is white'
        ]
    ]
]);
?>

And htpaccess;
# Redirect images to webp-on-demand.php (if browser supports webp)
RewriteCond %{HTTP_ACCEPT} image/webp
RewriteRule ^(.*)\.(jpe?g|png)$ webp-on-demand.php?source=%{SCRIPT_FILENAME} [NC,L]

Is standard install as per instructions in tutorial, appreciate any help or clues.

Bob

**Comment by Skorefin** [comment]
Sorry guys, here is default webp-on-demand.php;

``<?php
require 'vendor/autoload.php';
use WebPConvert\WebPConvert;

$source = $_GET['source'];
$destination = $source . '.webp';

$success = WebPConvert::convertAndServe($source, $destination, [
    'fail' => 'original',
    'quality' => 'auto',
    'max-quality' => 80,
    'converters' => ['cwebp', 'gd', 'imagick', 'wpc', 'ewww'],
    'converter-options' => [
		'cwebp',
        'ewww' => [
            'key' => 'your-api-key-here'
        ],
        'wpc' => [
            'api-version' => 1,
            'url' => 'https://example.com/wpc.php',
            'api-key' => 'my dog is white'
        ]
    ]
]);
?>

**Comment by rosell-dk** [comment]
The "No converters could convert the image" means that no of the conversion methods are working out of the box. Each converter has its own requirements. For example, the "gd" converter requires that the Gd extension is installed on the server, and that it is compiled with webp support.

Don't fret - you have options!

- If you a controlling a WordPress site (where the local conversion methods DO work), you can set up [WebP Express](https://wordpress.org/plugins/webp-express/) there, and then connect to it by configuring the “wpc” conversion method.
- You can also setup the ewww conversion method. To use it, you need to purchase an api key. They do not charge credits for webp conversions, so all you ever have to pay is the one dollar start-up fee 🙂 (unless they change their pricing – I have no control over that). You can buy an api key here: https://ewww.io/plans/
- If you are up to it, you can try to get one of the local converters working (gd, imagick, cwebp or gmagick). Check out [this page](https://github.com/rosell-dk/webp-convert/wiki/Meeting-the-requirements-of-the-converters) on the wiki
- Finally, if you have access to a server and are comfortable with installing projects with composer, you can install [webp-convert-cloud-service](https://github.com/rosell-dk/webp-convert-cloud-service). It's open source.
