### ISSUE TITLE
File name including space raise a 404 error

### ISSUE THREAD

**Issue by KokoKoder** [rosell-dk/webp-convert#95]
Issue seems to come from an encoding change between ASCII and either unicode  or UTF-8. Space are replaced by %20 in the file name.

**Comment by rosell-dk** [comment]
%20 seems to indicate that the space was url encoded. That would have happened *before* calling this library.

I just tested all converters with a filename including space. *cwebp* and *imagickbinary* both fails. The rest succeeds.

**Comment by KokoKoder** [comment]
yes, I did echo  $source and $destination and clear browser and site cache but all filename with space were displayed with %20 and returning 404 error.

**Comment by rosell-dk** [comment]
In webp-on-demand.php, there is a line which is commented out:
`//echo $source; exit;`

If you remove the comment and visit the image in the browser, what does it say?

**Comment by rosell-dk** [comment]
Btw, fortunately Wordpress seems to replace spaces with dashes, when you upload, so the impact is not major critical (not that it don't need fixing, obviously)

**Comment by rosell-dk** [comment]
How does the image url look?

**Comment by KokoKoder** [comment]
Not using composer so I don't have this line. Indeed leaving space in image name is not something I would recommend but I have a site with such files.  It looks that way: https://store.seobytes.eu/images/virtuemart/category/resized/CLIF%20komoda%20RTV%20-%20san%20remo%20&%20grafit%20mat_0x360.jpg

**Comment by rosell-dk** [comment]
oh, yeah, that is a new line.
Just copy it in immediately after $source is first assigned.

**Comment by rosell-dk** [comment]
Are you on Apache or Nginx?

**Comment by rosell-dk** [comment]
I am currently programming an option not to send the file name in the query string, but to rather use $_SERVER['REQUEST_URI']. It will be optional in 0.9. If it works well on all platforms, the option will be removed in 0.10, and there will be no more passing in query string.

You can help out testing this by setting $source like this in webp-on-demand.php:

```
    $requestUriNoQS = explode('?', $_SERVER['REQUEST_URI'])[0];
    $source = $docRoot . urldecode($requestUriNoQS);
```

**Comment by KokoKoder** [comment]
I am on Apache 
echo $source return the following string
/data01/virt64171/domeenid/www.seobytes.eu/store/images/virtuemart/category/resized/CLIF komoda RTV - san remo

**Comment by KokoKoder** [comment]
Nicely done, your fix worked.

**Comment by rosell-dk** [comment]
Ok. And where do you see the %20. In the filename in the converted file?

**Comment by KokoKoder** [comment]
It's actually in the navigation bar.

**Comment by KokoKoder** [comment]
I was sure I was missing something trivial here :D It should be imagick but can't say if it is binary or extension. How can I check that? 
Also can you specify to which URL shall I add '?debug' ?

**Comment by rosell-dk** [comment]
On WebP Express options page, you see a list of conversion methods. The first one with a green checkmark is the one that is going to be used.

The image url with ?debug added might look something like this:
http://example.com/wordpress/wp-content/uploads/space%20in%20name.jpg?debug

Adding ?debug tells webp convert to show a report of the conversion rather than the converted image

**Comment by KokoKoder** [comment]
might be gd extension  then but I am bot running wordpress on the website, so I am not on webp Express. I try to use webp convert as stand alone on server not running wordpress
in that circumstances ?debug give me only the image itself . I run WebP Express on another server with exactly the same config and it returns gd extension first and then Imagick extension and Imagick binary

**Comment by rosell-dk** [comment]
Ah, ok, happy to hear that the WebP On Demand solution is used :) I'm getting so many requests regarding WebP Express (which is based on WebP On Demand), that I just assumed you accidentally posted to this repo rather than WebP Express.

But, in that case - to trigger debug mode, simply set the 'show-report' option to `true`. The report will perhaps reveal what went wrong.

I have btw just released a bug release, 1.3.1, where cwebp and imagickbinary are able to convert images with filenames that contains spaces.

I'm off for weekend. Cheers

**Comment by KokoKoder** [comment]
I am also an advocate for html site whenever it makes sense :). I'll test the show report

**Comment by rosell-dk** [comment]
Perhaps the [NE](https://httpd.apache.org/docs/2.4/rewrite/flags.html#flag_ne) flag will kill the %20 bug?

In the RewriteRule, add "NE" to the flags.
ie:
```
RewriteRule ^(.*)\.(jpe?g|png)$ webp-on-demand.php?source=%{SCRIPT_FILENAME} [NC,NE,L]
```

Please let me know, thanks :)

**Comment by KokoKoder** [comment]
It gives a 404 too. (I removed the fix above to do the test). Same when enabling display error message
